#!/usr/bin/python3

import RPi.GPIO as GPIO
import sys

# 21 and 19 are one pair
# 26 and 13 are the other
GPIO.setmode(GPIO.BOARD)
GPIO.setup(26, GPIO.OUT)
GPIO.setup(19, GPIO.OUT)
GPIO.setup(13, GPIO.OUT)
GPIO.setup(21, GPIO.OUT)

GPIO.output(26, GPIO.LOW)
GPIO.output(19, GPIO.LOW)
GPIO.output(13, GPIO.LOW)
GPIO.output(21, GPIO.LOW)

GPIO.cleanup()
